---

_You are currently looking at **version 1.2** of this notebook. To download notebooks and datafiles, as well as get help on Jupyter notebooks in the Coursera platform, visit the [Jupyter Notebook FAQ](https://www.coursera.org/learn/python-data-analysis/resources/0dhYG) course resource._

---

# Assignment 2 - Pandas Introduction
All questions are weighted the same in this assignment.
## Part 1
The following code loads the olympics dataset (olympics.csv), which was derrived from the Wikipedia entry on [All Time Olympic Games Medals](https://en.wikipedia.org/wiki/All-time_Olympic_Games_medal_table), and does some basic data cleaning. 

The columns are organized as # of Summer games, Summer medals, # of Winter games, Winter medals, total # number of games, total # of medals. Use this dataset to answer the questions below.

In [ ]:
import pandas as pd

df = pd.read_csv('olympics.csv', index_col=0, skiprows=1)

for col in df.columns:
    if col[:2]=='01':
        df.rename(columns={col:'Gold'+col[4:]}, inplace=True)
    if col[:2]=='02':
        df.rename(columns={col:'Silver'+col[4:]}, inplace=True)
    if col[:2]=='03':
        df.rename(columns={col:'Bronze'+col[4:]}, inplace=True)
    if col[:1]=='â„–':
        df.rename(columns={col:'#'+col[1:]}, inplace=True)

names_ids = df.index.str.split('\s\(') # split the index by '('

df.index = names_ids.str[0] # the [0] element is the country name (new index) 
df['ID'] = names_ids.str[1].str[:3] # the [1] element is the abbreviation or ID (take first 3 characters from that)

df = df.drop('Totals')
df.head()

### Question 0 (Example)

What is the first country in df?

*This function should return a Series.*

In [ ]:
# You should write your whole answer within the function provided. The autograder will call
# this function and compare the return value against the correct solution value
def answer_zero():
    # This function returns the row for Afghanistan, which is a Series object. The assignment
    # question description will tell you the general format the autograder is expecting
    return df.iloc[0]

# You can examine what your function returns by calling it in the cell. If you have questions
# about the assignment formats, check out the discussion forums for any FAQs
answer_zero()

### Question 1
Which country has won the most gold medals in summer games?

*This function should return a single string value.*

In [ ]:
def answer_one():
    df1 = df.copy()
    
    summer_gold = df1.where(df1['Gold']>0)
    summer_gold = summer_gold.dropna()
    
    most_medal = 0
    for country in summer_gold['Gold']:
        if country > most_medal:
            most_medal = country
    return (df1[(df1['Gold'] == most_medal)]).index[0]
#answer_one()

### Question 2
Which country had the biggest difference between their summer and winter gold medal counts?

*This function should return a single string value.*

In [ ]:
def answer_two():
    df2 = df.copy()
    
    difference =(df2['Gold'] - df2['Gold.1'])
    return df2[df2['Gold'] - df2['Gold.1']==max(difference)].index[0]
#answer_two()

### Question 3
Which country has the biggest difference between their summer gold medal counts and winter gold medal counts relative to their total gold medal count? 

$$\frac{Summer~Gold - Winter~Gold}{Total~Gold}$$

Only include countries that have won at least 1 gold in both summer and winter.

*This function should return a single string value.*

In [ ]:
def answer_three():
    df3 = df.copy()
    
    df3 = df3[(df3['Gold'] > 0) & (df3['Gold.1'] > 0)]
    df3 = df3.dropna()

    diff = (df3['Gold'] - df3['Gold.1'])
    formula_sw = diff/(df3['Gold.2'])

    return df3[(df3['Gold'] - df3['Gold.1'])/(df3['Gold.2']) == max(formula_sw)].index[0]
#answer_three()

### Question 4
Write a function that creates a Series called "Points" which is a weighted value where each gold medal (`Gold.2`) counts for 3 points, silver medals (`Silver.2`) for 2 points, and bronze medals (`Bronze.2`) for 1 point. The function should return only the column (a Series object) which you created.

*This function should return a Series named `Points` of length 146*

In [ ]:
def answer_four():
    df4 = df.copy()
    
    my_data1 = df['Gold.2']
    my_data2 = df['Silver.2']
    my_data3 = df['Bronze.2']
    
    Points = 3*my_data1 + 2*my_data2 + my_data3
    return Points
#answer_four()

## Part 2
For the next set of questions, we will be using census data from the [United States Census Bureau](http://www.census.gov/popest/data/counties/totals/2015/CO-EST2015-alldata.html). Counties are political and geographic subdivisions of states in the United States. This dataset contains population data for counties and states in the US from 2010 to 2015. [See this document](http://www.census.gov/popest/data/counties/totals/2015/files/CO-EST2015-alldata.pdf) for a description of the variable names.

The census dataset (census.csv) should be loaded as census_df. Answer questions using this as appropriate.

### Question 5
Which state has the most counties in it? (hint: consider the sumlevel key carefully! You'll need this for future questions too...)

*This function should return a single string value.*

The link in the assignment for the documentation of the US census data used in Part 2 no longer works because the US government has updated their website, the new link is:

https://www2.census.gov/programs-surveys/popest/datasets/2010-2015/counties/totals/co-est2015-alldata.pdf

In case you have difficulties retrieving it, here is the description of an important column:

The key for SUMLEV is as follows:

    040 = State and/or Statistical Equivalent
    050 = County and /or Statistical Equivalent

In [14]:
import pandas as pd
import numpy as np

census_df = pd.read_csv('census.csv')
census_df.head()

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
0,40,3,6,1,0,Alabama,Alabama,4779736,4780127,4785161,...,0.002295,-0.193196,0.381066,0.582002,-0.467369,1.030015,0.826644,1.383282,1.724718,0.712594
1,50,3,6,1,1,Alabama,Autauga County,54571,54571,54660,...,7.242091,-2.915927,-3.012349,2.265971,-2.530799,7.606016,-2.626146,-2.722002,2.592270,-2.187333
2,50,3,6,1,3,Alabama,Baldwin County,182265,182265,183193,...,14.832960,17.647293,21.845705,19.243287,17.197872,15.844176,18.559627,22.727626,20.317142,18.293499
3,50,3,6,1,5,Alabama,Barbour County,27457,27457,27341,...,-4.728132,-2.500690,-7.056824,-3.904217,-10.543299,-4.874741,-2.758113,-7.167664,-3.978583,-10.543299
4,50,3,6,1,7,Alabama,Bibb County,22915,22919,22861,...,-5.527043,-5.068871,-6.201001,-0.177537,0.177258,-5.088389,-4.363636,-5.403729,0.754533,1.107861

In [ ]:
def answer_five():
    counties = census_df.where(census_df['SUMLEV'] == 50)
    counties = counties.dropna()
    states = counties['STNAME'].unique()

    state_df = pd.DataFrame()
    state_df['States'] = states
    state_df['CountyCount'] = 0
    state_df.set_index('States', inplace = True)

    for st in state_df.index:
        stcount = len(counties[counties['STNAME'] == st])
        state_df['CountyCount'].loc[st] = stcount

    return (state_df.idxmax()[0])
#answer_five()

### Question 6
Only looking at the three most populous counties for each state, what are the three most populous states (in order of highest population to lowest population)? Use `CENSUS2010POP`.

*This function should return a list of string values.*

In [6]:
def answer_six():
    part2_df = pd.read_csv('census.csv')
    counties = part2_df.where(part2_df['SUMLEV'] == 50)
    counties = counties.dropna()
    states = counties['STNAME'].unique()

    col_to_keep = ['STNAME', 'CTYNAME', 'SUMLEV', 'CENSUS2010POP']
    counties2 = counties[col_to_keep]
    most_populus_counties = []
    
    state_df2 = pd.DataFrame()
    state_df2['States'] = states
    state_df2['Populus'] = 0
    state_df2.set_index('States', inplace = True)

    for st in state_df2.index:
        pop_counties = (counties2[counties2['STNAME'] == st]).sort_values(by='CENSUS2010POP',ascending=False).head(3)
        most_populus_counties= sum(pop_counties['CENSUS2010POP'])
        state_df2['Populus'].loc[st] = most_populus_counties
    
    return state_df2.sort_values(by= 'Populus', ascending=False).head(3).index.tolist()
#answer_six()

### Question 7
Which county has had the largest absolute change in population within the period 2010-2015? (Hint: population values are stored in columns POPESTIMATE2010 through POPESTIMATE2015, you need to consider all six columns.)

e.g. If County Population in the 5 year period is 100, 120, 80, 105, 100, 130, then its largest change in the period would be |130-80| = 50.

*This function should return a single string value.*

In [19]:
def calculate_diff(row):
    data = row[['POPESTIMATE2010','POPESTIMATE2011','POPESTIMATE2012','POPESTIMATE2013','POPESTIMATE2014',
               'POPESTIMATE2015']]
    row['max'] = np.max(data)
    row['min'] = np.min(data)
    row['diff'] = row['max'] - row['min']
    return row['diff']

In [16]:
def answer_seven():
    parttwo_df = pd.read_csv('census.csv')

    helper = ['POPESTIMATE2010','POPESTIMATE2011','POPESTIMATE2012','POPESTIMATE2013','POPESTIMATE2014',
              'POPESTIMATE2015']
    
    my_columns = ['STNAME', 'CTYNAME', 'SUMLEV'] + helper
    q7 = parttwo_df[my_columns]
    q7 = q7.where(q7['SUMLEV'] == 50).dropna().set_index(['STNAME', 'CTYNAME'])
    return pd.DataFrame(
        q7.apply(calculate_diff, axis = 1),
                 columns = ['diff']).nlargest(1, columns='diff').index[0][1]

### Question 8
In this datafile, the United States is broken up into four regions using the "REGION" column. 

Create a query that finds the counties that belong to regions 1 or 2, whose name starts with 'Washington', and whose POPESTIMATE2015 was greater than their POPESTIMATE 2014.

*This function should return a 5x2 DataFrame with the columns = ['STNAME', 'CTYNAME'] and the same index ID as the census_df (sorted ascending by index).*

In [22]:
def answer_eight():
    parttwo_df = pd.read_csv('census.csv')
    helper = ['REGION','POPESTIMATE2015','POPESTIMATE2014']
    my_columns = ['STNAME', 'CTYNAME', 'SUMLEV'] + helper

    question8_df = parttwo_df[my_columns]
    question8_df = question8_df.where(question8_df['SUMLEV'] == 50)
    question8_df = question8_df.dropna()
    state_list = question8_df['STNAME'].unique()
    county_list = question8_df['CTYNAME']

    new_q8_df = question8_df.copy()
    new_q8_df.set_index('CTYNAME', inplace = True)

    filter_df = question8_df[(question8_df['CTYNAME'].str.startswith('Washington')) & (question8_df['POPESTIMATE2015'] > question8_df['POPESTIMATE2014']) & (question8_df['REGION'].isin([1,2]))]
    answer = pd.DataFrame(filter_df[['CTYNAME','STNAME']].head())
    return answer

#answer_eight()

                CTYNAME        STNAME
896   Washington County          Iowa
1419  Washington County     Minnesota
2345  Washington County  Pennsylvania
2355  Washington County  Rhode Island
3163  Washington County     Wisconsin